import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import Navbar from "@/components/UI/Navbar";
import Footer from "@/components/UI/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} container mx-auto border-[1px] border-zinc-700 shadow-lg my-5 p-2 rounded-2xl text-white bg-zinc-950 h-full overflow-x-auto`}
      >
        <AntdRegistry>
          <div className="bg-white p-2 rounded-xl ">
            <Navbar />
            <div className="py-5">{children}</div>
            <Footer />
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
